version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dtprimum
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
